"""
Feature Type-Wise Performance Analysis
=======================================
Project : Speech-Based Parkinson's Disease Detection (BE Capstone)
Author  : Generated by Claude

PURPOSE:
    Analyze model performance by feature category to identify which
    feature types are most cross-lingually invariant.
    
    Based on mentor meeting (2026-03-23):
    "Breakdown of model performance by feature category:
     - All features (baseline)
     - Spectral features only
     - Prosodic features only
     - K-best combined (9, 20, 30)"

FEATURE CATEGORIES (from Literature_Survey_PD.xlsx):
    1. Phonatory (Biomarkers): jitter, shimmer, HNR, NHR
    2. F0/Prosodic: Fundamental frequency features
    3. MFCC: Mel-frequency cepstral coefficients
    4. Delta MFCC: First derivative of MFCC
    5. Delta-Delta MFCC: Second derivative of MFCC
    6. Spectral Other: centroid, bandwidth, rolloff, flux
    7. Energy/ZCR: Log energy, zero-crossing rate
    8. Chroma: Pitch-class profiles
    9. Mel: Mel spectrogram summary

EXPERIMENTS:
    - Within-dataset (5-fold CV on each dataset)
    - Cross-dataset (train on ES, test on IT; train on IT, test on ES)

OUTPUT:
    - Performance comparison table (AUC, Accuracy, F1)
    - Best confusion matrix per category
    - Summary plots
"""

import os
import warnings
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import (
    roc_auc_score, accuracy_score, f1_score, 
    confusion_matrix, classification_report
)
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

# ============================================================================
# CONFIG
# ============================================================================

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

INPUT_DIR = '/home/z/my-project/download'
OUTPUT_DIR = '/home/z/my-project/download'

# Balanced datasets
PCGITA_CSV = os.path.join(INPUT_DIR, 'features_pcgita_balanced_a_only.csv')
VOICED_CSV = os.path.join(INPUT_DIR, 'features_voiced_balanced_a_matched.csv')

# Meta columns to exclude
META_COLS = {
    'dataset', 'subject_id', 'language', 'gender', 'speech_type',
    'disease_label', 'label_binary', 'label', 'file',
    'rms_original', 'rms_after', 'rms_target', 'rms_clipped', 'duration_s'
}

# ============================================================================
# FEATURE CATEGORIES (based on Literature_Survey_PD.xlsx)
# ============================================================================

FEATURE_CATEGORIES = {
    'Phonatory (Biomarkers)': [
        'jitter_local', 'jitter_rap', 'jitter_ppq5', 'jitter_ddp',
        'shimmer_local', 'shimmer_apq3', 'shimmer_apq5', 'shimmer_apq11', 'shimmer_dda',
        'hnr', 'nhr'
    ],
    'F0/Prosodic': [
        'praat_f0_mean', 'praat_f0_std', 'praat_f0_min', 'praat_f0_max', 
        'praat_f0_range', 'praat_f0_median'
    ],
    'MFCC': [
        'mfcc_01_mean', 'mfcc_02_mean', 'mfcc_03_mean', 'mfcc_04_mean', 'mfcc_05_mean',
        'mfcc_06_mean', 'mfcc_07_mean', 'mfcc_08_mean', 'mfcc_09_mean', 'mfcc_10_mean',
        'mfcc_11_mean', 'mfcc_12_mean', 'mfcc_13_mean',
        'mfcc_01_std', 'mfcc_02_std', 'mfcc_03_std', 'mfcc_04_std', 'mfcc_05_std',
        'mfcc_06_std', 'mfcc_07_std', 'mfcc_08_std', 'mfcc_09_std', 'mfcc_10_std',
        'mfcc_11_std', 'mfcc_12_std', 'mfcc_13_std'
    ],
    'Delta MFCC': [
        'dmfcc_01_mean', 'dmfcc_02_mean', 'dmfcc_03_mean', 'dmfcc_04_mean', 'dmfcc_05_mean',
        'dmfcc_06_mean', 'dmfcc_07_mean', 'dmfcc_08_mean', 'dmfcc_09_mean', 'dmfcc_10_mean',
        'dmfcc_11_mean', 'dmfcc_12_mean', 'dmfcc_13_mean'
    ],
    'Delta-Delta MFCC': [
        'd2mfcc_01_mean', 'd2mfcc_02_mean', 'd2mfcc_03_mean', 'd2mfcc_04_mean', 'd2mfcc_05_mean',
        'd2mfcc_06_mean', 'd2mfcc_07_mean', 'd2mfcc_08_mean', 'd2mfcc_09_mean', 'd2mfcc_10_mean',
        'd2mfcc_11_mean', 'd2mfcc_12_mean', 'd2mfcc_13_mean'
    ],
    'Spectral Other': [
        'spectral_centroid_mean', 'spectral_centroid_std',
        'spectral_bandwidth_mean', 'spectral_bandwidth_std',
        'spectral_rolloff_mean', 'spectral_flux_mean', 'spectral_flux_std'
    ],
    'Energy/ZCR': [
        'log_energy_mean', 'log_energy_std', 'zcr_mean', 'zcr_std'
    ],
    'Chroma': [
        'chroma_00_mean', 'chroma_00_std', 'chroma_01_mean', 'chroma_01_std',
        'chroma_02_mean', 'chroma_02_std', 'chroma_03_mean', 'chroma_03_std',
        'chroma_04_mean', 'chroma_04_std', 'chroma_05_mean', 'chroma_05_std',
        'chroma_06_mean', 'chroma_06_std', 'chroma_07_mean', 'chroma_07_std',
        'chroma_08_mean', 'chroma_08_std', 'chroma_09_mean', 'chroma_09_std',
        'chroma_10_mean', 'chroma_10_std', 'chroma_11_mean', 'chroma_11_std'
    ],
    'Mel': ['mel_mean', 'mel_std'],
}

# Feature combinations (for higher-level analysis)
FEATURE_COMBINATIONS = {
    'All Features': None,  # Will be computed dynamically
    'Phonatory + F0': ['Phonatory (Biomarkers)', 'F0/Prosodic'],
    'All MFCC': ['MFCC', 'Delta MFCC', 'Delta-Delta MFCC'],
    'All Spectral': ['MFCC', 'Delta MFCC', 'Delta-Delta MFCC', 'Spectral Other', 'Chroma', 'Mel', 'Energy/ZCR'],
}

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_available_features(df, category_features):
    """Get features that exist and are not all NaN in the dataframe."""
    available = []
    for f in category_features:
        if f in df.columns:
            if not df[f].isna().all():
                available.append(f)
    return available


def get_features_for_category(df, category_name):
    """Get features for a single category."""
    if category_name not in FEATURE_CATEGORIES:
        return []
    return get_available_features(df, FEATURE_CATEGORIES[category_name])


def get_features_for_combination(df, combination_name):
    """Get features for a combination of categories."""
    if combination_name == 'All Features':
        # All non-meta, non-NaN features
        all_feats = [c for c in df.columns if c not in META_COLS]
        return [f for f in all_feats if not df[f].isna().all()]
    
    if combination_name not in FEATURE_COMBINATIONS:
        return []
    
    features = []
    for cat in FEATURE_COMBINATIONS[combination_name]:
        features.extend(get_features_for_category(df, cat))
    return list(set(features))  # Remove duplicates


def evaluate_within_dataset(X, y, n_folds=5):
    """Evaluate within-dataset using stratified cross-validation."""
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    clf = RandomForestClassifier(
        n_estimators=100, 
        max_depth=10, 
        random_state=RANDOM_SEED,
        n_jobs=-1
    )
    
    cv = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=RANDOM_SEED)
    
    aucs = cross_val_score(clf, X_scaled, y, cv=cv, scoring='roc_auc')
    accs = cross_val_score(clf, X_scaled, y, cv=cv, scoring='accuracy')
    f1s = cross_val_score(clf, X_scaled, y, cv=cv, scoring='f1')
    
    return {
        'auc_mean': aucs.mean(),
        'auc_std': aucs.std(),
        'acc_mean': accs.mean(),
        'acc_std': accs.std(),
        'f1_mean': f1s.mean(),
        'f1_std': f1s.std(),
    }


def evaluate_cross_dataset(X_train, y_train, X_test, y_test):
    """Evaluate cross-dataset: train on one, test on another."""
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    clf = RandomForestClassifier(
        n_estimators=100, 
        max_depth=10, 
        random_state=RANDOM_SEED,
        n_jobs=-1
    )
    clf.fit(X_train_scaled, y_train)
    
    y_pred = clf.predict(X_test_scaled)
    y_proba = clf.predict_proba(X_test_scaled)[:, 1]
    
    return {
        'auc': roc_auc_score(y_test, y_proba),
        'accuracy': accuracy_score(y_test, y_pred),
        'f1': f1_score(y_test, y_pred),
        'confusion_matrix': confusion_matrix(y_test, y_pred),
        'y_test': y_test,
        'y_pred': y_pred,
        'y_proba': y_proba,
    }


def run_experiment(pcgita_df, voiced_df, feature_list, exp_name):
    """Run all experiments for a feature set."""
    results = {}
    
    # Check if features exist in both datasets
    pcgita_features = [f for f in feature_list if f in pcgita_df.columns and not pcgita_df[f].isna().all()]
    voiced_features = [f for f in feature_list if f in voiced_df.columns and not voiced_df[f].isna().all()]
    
    # Use intersection of available features
    common_features = list(set(pcgita_features) & set(voiced_features))
    
    if len(common_features) == 0:
        print(f"  [{exp_name}] No common features available, skipping...")
        return None
    
    if len(common_features) < 3:
        print(f"  [{exp_name}] Only {len(common_features)} features, skipping...")
        return None
    
    print(f"  [{exp_name}] Using {len(common_features)} features")
    
    # Prepare data
    X_pcgita = pcgita_df[common_features].fillna(pcgita_df[common_features].median())
    y_pcgita = pcgita_df['label_binary'].values
    
    X_voiced = voiced_df[common_features].fillna(voiced_df[common_features].median())
    y_voiced = voiced_df['label_binary'].values
    
    # Within-dataset: PC-GITA
    print(f"    Within PC-GITA (5-fold CV)...")
    results['pcgita_within'] = evaluate_within_dataset(X_pcgita.values, y_pcgita)
    
    # Within-dataset: VOICED
    print(f"    Within VOICED (5-fold CV)...")
    results['voiced_within'] = evaluate_within_dataset(X_voiced.values, y_voiced)
    
    # Cross-dataset: ES -> IT
    print(f"    Cross ES->IT...")
    results['es_to_it'] = evaluate_cross_dataset(X_pcgita.values, y_pcgita, X_voiced.values, y_voiced)
    
    # Cross-dataset: IT -> ES
    print(f"    Cross IT->ES...")
    results['it_to_es'] = evaluate_cross_dataset(X_voiced.values, y_voiced, X_pcgita.values, y_pcgita)
    
    results['n_features'] = len(common_features)
    results['features'] = common_features
    
    return results


def plot_confusion_matrix(cm, title, ax):
    """Plot confusion matrix."""
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['HC', 'PD'], yticklabels=['HC', 'PD'])
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')
    ax.set_title(title)


def plot_results(all_results, output_dir):
    """Generate comprehensive plots."""
    # Prepare data for plotting
    categories = []
    for name in list(FEATURE_CATEGORIES.keys()) + list(FEATURE_COMBINATIONS.keys()):
        if name in all_results and all_results[name] is not None:
            categories.append(name)
    
    # Plot 1: Performance comparison bar chart
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    
    # AUC comparison
    ax = axes[0, 0]
    x = np.arange(len(categories))
    width = 0.35
    
    es_within_aucs = [all_results[c]['pcgita_within']['auc_mean'] for c in categories]
    it_within_aucs = [all_results[c]['voiced_within']['auc_mean'] for c in categories]
    
    ax.bar(x - width/2, es_within_aucs, width, label='PC-GITA (ES)', color='#1565C0')
    ax.bar(x + width/2, it_within_aucs, width, label='VOICED (IT)', color='#2E7D32')
    ax.set_ylabel('AUC')
    ax.set_title('Within-Dataset AUC (5-fold CV)')
    ax.set_xticks(x)
    ax.set_xticklabels([c[:15] + '...' if len(c) > 15 else c for c in categories], rotation=45, ha='right')
    ax.legend()
    ax.axhline(0.5, color='gray', linestyle='--', alpha=0.5)
    ax.set_ylim(0.4, 1.0)
    
    # Cross-dataset AUC
    ax = axes[0, 1]
    es_to_it_aucs = [all_results[c]['es_to_it']['auc'] for c in categories]
    it_to_es_aucs = [all_results[c]['it_to_es']['auc'] for c in categories]
    
    ax.bar(x - width/2, es_to_it_aucs, width, label='ES → IT', color='#1565C0')
    ax.bar(x + width/2, it_to_es_aucs, width, label='IT → ES', color='#2E7D32')
    ax.set_ylabel('AUC')
    ax.set_title('Cross-Dataset AUC')
    ax.set_xticks(x)
    ax.set_xticklabels([c[:15] + '...' if len(c) > 15 else c for c in categories], rotation=45, ha='right')
    ax.legend()
    ax.axhline(0.5, color='gray', linestyle='--', alpha=0.5)
    ax.set_ylim(0.4, 1.0)
    
    # F1 comparison
    ax = axes[1, 0]
    es_within_f1s = [all_results[c]['pcgita_within']['f1_mean'] for c in categories]
    it_within_f1s = [all_results[c]['voiced_within']['f1_mean'] for c in categories]
    
    ax.bar(x - width/2, es_within_f1s, width, label='PC-GITA (ES)', color='#1565C0')
    ax.bar(x + width/2, it_within_f1s, width, label='VOICED (IT)', color='#2E7D32')
    ax.set_ylabel('F1 Score')
    ax.set_title('Within-Dataset F1 (5-fold CV)')
    ax.set_xticks(x)
    ax.set_xticklabels([c[:15] + '...' if len(c) > 15 else c for c in categories], rotation=45, ha='right')
    ax.legend()
    ax.set_ylim(0.4, 1.0)
    
    # Cross-dataset F1
    ax = axes[1, 1]
    es_to_it_f1s = [all_results[c]['es_to_it']['f1'] for c in categories]
    it_to_es_f1s = [all_results[c]['it_to_es']['f1'] for c in categories]
    
    ax.bar(x - width/2, es_to_it_f1s, width, label='ES → IT', color='#1565C0')
    ax.bar(x + width/2, it_to_es_f1s, width, label='IT → ES', color='#2E7D32')
    ax.set_ylabel('F1 Score')
    ax.set_title('Cross-Dataset F1')
    ax.set_xticks(x)
    ax.set_xticklabels([c[:15] + '...' if len(c) > 15 else c for c in categories], rotation=45, ha='right')
    ax.legend()
    ax.set_ylim(0.4, 1.0)
    
    plt.suptitle('Feature Type-Wise Performance Analysis\nPC-GITA (Spanish) vs VOICED (Italian) - Vowel /a/ only', 
                 fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'feature_type_performance.png'), dpi=150, bbox_inches='tight')
    plt.close()
    
    # Plot 2: Best confusion matrices
    # Find best performing category for cross-dataset
    best_es_to_it = max(categories, key=lambda c: all_results[c]['es_to_it']['auc'])
    best_it_to_es = max(categories, key=lambda c: all_results[c]['it_to_es']['auc'])
    
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    
    # Top row: ES->IT confusion matrices
    for i, (cat, ax) in enumerate(zip(['All Features', 'Phonatory + F0', 'All MFCC', best_es_to_it], axes[0])):
        if cat in all_results and all_results[cat] is not None:
            cm = all_results[cat]['es_to_it']['confusion_matrix']
            auc = all_results[cat]['es_to_it']['auc']
            plot_confusion_matrix(cm, f'{cat}\nES→IT AUC={auc:.3f}', ax)
    
    # Bottom row: IT->ES confusion matrices
    for i, (cat, ax) in enumerate(zip(['All Features', 'Phonatory + F0', 'All MFCC', best_it_to_es], axes[1])):
        if cat in all_results and all_results[cat] is not None:
            cm = all_results[cat]['it_to_es']['confusion_matrix']
            auc = all_results[cat]['it_to_es']['auc']
            plot_confusion_matrix(cm, f'{cat}\nIT→ES AUC={auc:.3f}', ax)
    
    plt.suptitle('Confusion Matrices - Cross-Dataset Performance', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'confusion_matrices.png'), dpi=150, bbox_inches='tight')
    plt.close()
    
    # Plot 3: Feature count vs Performance
    fig, ax = plt.subplots(figsize=(12, 6))
    
    n_feats = [all_results[c]['n_features'] for c in categories]
    cross_aucs = [(all_results[c]['es_to_it']['auc'] + all_results[c]['it_to_es']['auc']) / 2 for c in categories]
    within_aucs = [(all_results[c]['pcgita_within']['auc_mean'] + all_results[c]['voiced_within']['auc_mean']) / 2 for c in categories]
    
    ax.scatter(n_feats, within_aucs, s=100, c='#1565C0', label='Within-Dataset (avg)', alpha=0.7)
    ax.scatter(n_feats, cross_aucs, s=100, c='#E65100', label='Cross-Dataset (avg)', alpha=0.7)
    
    for i, cat in enumerate(categories):
        ax.annotate(cat[:10], (n_feats[i], cross_aucs[i]), fontsize=7, alpha=0.7)
    
    ax.set_xlabel('Number of Features')
    ax.set_ylabel('AUC')
    ax.set_title('Feature Count vs Performance')
    ax.legend()
    ax.axhline(0.5, color='gray', linestyle='--', alpha=0.5)
    ax.set_ylim(0.4, 1.0)
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'feature_count_vs_performance.png'), dpi=150, bbox_inches='tight')
    plt.close()


def generate_summary_table(all_results):
    """Generate summary table for thesis."""
    rows = []
    
    for name in list(FEATURE_CATEGORIES.keys()) + list(FEATURE_COMBINATIONS.keys()):
        if name not in all_results or all_results[name] is None:
            continue
        
        r = all_results[name]
        rows.append({
            'Feature Category': name,
            'N Features': r['n_features'],
            'ES Within AUC': f"{r['pcgita_within']['auc_mean']:.3f} ± {r['pcgita_within']['auc_std']:.3f}",
            'IT Within AUC': f"{r['voiced_within']['auc_mean']:.3f} ± {r['voiced_within']['auc_std']:.3f}",
            'ES→IT AUC': f"{r['es_to_it']['auc']:.3f}",
            'IT→ES AUC': f"{r['it_to_es']['auc']:.3f}",
            'ES Within F1': f"{r['pcgita_within']['f1_mean']:.3f} ± {r['pcgita_within']['f1_std']:.3f}",
            'IT Within F1': f"{r['voiced_within']['f1_mean']:.3f} ± {r['voiced_within']['f1_std']:.3f}",
            'ES→IT F1': f"{r['es_to_it']['f1']:.3f}",
            'IT→ES F1': f"{r['it_to_es']['f1']:.3f}",
        })
    
    return pd.DataFrame(rows)


# ============================================================================
# MAIN
# ============================================================================

def main():
    print("=" * 70)
    print("FEATURE TYPE-WISE PERFORMANCE ANALYSIS")
    print("=" * 70)
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()
    
    # Load data
    print("Loading balanced datasets...")
    pcgita_df = pd.read_csv(PCGITA_CSV)
    voiced_df = pd.read_csv(VOICED_CSV)
    print(f"  PC-GITA: {len(pcgita_df)} samples (96 PD, 96 HC)")
    print(f"  VOICED:  {len(voiced_df)} samples (133 PD, 133 HC)")
    print()
    
    all_results = {}
    
    # Run experiments for each category
    print("=" * 70)
    print("SINGLE FEATURE CATEGORIES")
    print("=" * 70)
    
    for cat_name, cat_features in FEATURE_CATEGORIES.items():
        print(f"\n[{cat_name}]")
        available = get_available_features(pcgita_df, cat_features)
        print(f"  Defined: {len(cat_features)} features")
        print(f"  Available: {len(available)} features")
        
        results = run_experiment(pcgita_df, voiced_df, cat_features, cat_name)
        all_results[cat_name] = results
        
        if results:
            print(f"  Results:")
            print(f"    ES Within AUC: {results['pcgita_within']['auc_mean']:.3f}")
            print(f"    IT Within AUC: {results['voiced_within']['auc_mean']:.3f}")
            print(f"    ES→IT AUC:     {results['es_to_it']['auc']:.3f}")
            print(f"    IT→ES AUC:     {results['it_to_es']['auc']:.3f}")
    
    # Run experiments for combinations
    print("\n" + "=" * 70)
    print("FEATURE COMBINATIONS")
    print("=" * 70)
    
    for comb_name in FEATURE_COMBINATIONS.keys():
        print(f"\n[{comb_name}]")
        
        if comb_name == 'All Features':
            features = [c for c in pcgita_df.columns if c not in META_COLS]
            features = [f for f in features if not pcgita_df[f].isna().all() and not voiced_df[f].isna().all()]
        else:
            features = get_features_for_combination(pcgita_df, comb_name)
        
        print(f"  Features: {len(features)}")
        
        results = run_experiment(pcgita_df, voiced_df, features, comb_name)
        all_results[comb_name] = results
        
        if results:
            print(f"  Results:")
            print(f"    ES Within AUC: {results['pcgita_within']['auc_mean']:.3f}")
            print(f"    IT Within AUC: {results['voiced_within']['auc_mean']:.3f}")
            print(f"    ES→IT AUC:     {results['es_to_it']['auc']:.3f}")
            print(f"    IT→ES AUC:     {results['it_to_es']['auc']:.3f}")
    
    # Generate outputs
    print("\n" + "=" * 70)
    print("GENERATING OUTPUTS")
    print("=" * 70)
    
    # Summary table
    summary_df = generate_summary_table(all_results)
    summary_path = os.path.join(OUTPUT_DIR, 'feature_type_summary.csv')
    summary_df.to_csv(summary_path, index=False)
    print(f"\nSummary table saved: {summary_path}")
    print("\n" + summary_df.to_string())
    
    # Plots
    print("\nGenerating plots...")
    plot_results(all_results, OUTPUT_DIR)
    print(f"  feature_type_performance.png")
    print(f"  confusion_matrices.png")
    print(f"  feature_count_vs_performance.png")
    
    # Detailed results
    detailed_path = os.path.join(OUTPUT_DIR, 'feature_type_detailed_results.csv')
    detailed_rows = []
    for name, r in all_results.items():
        if r is None:
            continue
        detailed_rows.append({
            'Category': name,
            'N_Features': r['n_features'],
            'ES_Within_AUC_Mean': r['pcgita_within']['auc_mean'],
            'ES_Within_AUC_Std': r['pcgita_within']['auc_std'],
            'IT_Within_AUC_Mean': r['voiced_within']['auc_mean'],
            'IT_Within_AUC_Std': r['voiced_within']['auc_std'],
            'ES_to_IT_AUC': r['es_to_it']['auc'],
            'IT_to_ES_AUC': r['it_to_es']['auc'],
            'ES_Within_Acc_Mean': r['pcgita_within']['acc_mean'],
            'IT_Within_Acc_Mean': r['voiced_within']['acc_mean'],
            'ES_to_IT_Acc': r['es_to_it']['accuracy'],
            'IT_to_ES_Acc': r['it_to_es']['accuracy'],
            'ES_Within_F1_Mean': r['pcgita_within']['f1_mean'],
            'IT_Within_F1_Mean': r['voiced_within']['f1_mean'],
            'ES_to_IT_F1': r['es_to_it']['f1'],
            'IT_to_ES_F1': r['it_to_es']['f1'],
        })
    pd.DataFrame(detailed_rows).to_csv(detailed_path, index=False)
    print(f"  feature_type_detailed_results.csv")
    
    # Key findings
    print("\n" + "=" * 70)
    print("KEY FINDINGS")
    print("=" * 70)
    
    # Find best performing categories
    valid_results = {k: v for k, v in all_results.items() if v is not None}
    
    best_cross = max(valid_results.items(), key=lambda x: (x[1]['es_to_it']['auc'] + x[1]['it_to_es']['auc']) / 2)
    best_within = max(valid_results.items(), key=lambda x: (x[1]['pcgita_within']['auc_mean'] + x[1]['voiced_within']['auc_mean']) / 2)
    
    print(f"\nBest Cross-Dataset Performance: {best_cross[0]}")
    print(f"  Average Cross AUC: {(best_cross[1]['es_to_it']['auc'] + best_cross[1]['it_to_es']['auc']) / 2:.3f}")
    
    print(f"\nBest Within-Dataset Performance: {best_within[0]}")
    print(f"  Average Within AUC: {(best_within[1]['pcgita_within']['auc_mean'] + best_within[1]['voiced_within']['auc_mean']) / 2:.3f}")
    
    # Compare biomarkers vs full features
    if 'Phonatory + F0' in valid_results and 'All Features' in valid_results:
        bio = valid_results['Phonatory + F0']
        full = valid_results['All Features']
        
        print(f"\nBiomarkers vs All Features (Cross-Dataset):")
        print(f"  Biomarkers: ES→IT={bio['es_to_it']['auc']:.3f}, IT→ES={bio['it_to_es']['auc']:.3f}")
        print(f"  All Features: ES→IT={full['es_to_it']['auc']:.3f}, IT→ES={full['it_to_es']['auc']:.3f}")
    
    print("\n" + "=" * 70)
    print(f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)


if __name__ == "__main__":
    main()
